argoproj-labs/argocd-agent

agent/agent.go
pkg/client/remote.go

fix: Fix reconnect logic

---

cmd/agent/main.go
cmd/cmd/log.go
cmd/principal/main.go

Some log levels go to stderr, others to stdout.

feat: Support logging to different output streams

---

install/kubernetes/agent/agent-deployment.yaml
install/kubernetes/agent/agent-params-cm.yaml

This PR fixes the manifest to use correct config maps keys in deployment

fix: fix agent resources manifest

---

cmd/principal/main.go
go.mod
install/kubernetes/principal/principal-deployment.yaml
install/kubernetes/principal/principal-params-cm.yaml
internal/labels/parser.go
internal/labels/parser_test.go
principal/event.go
principal/event_test.go
principal/options.go
principal/server.go

feat: Automatic creation of namespaces on control plane for autonomous agents

---

README.md

Use a markdown warning to highlight current status.

docs: Highlight non-production status

---

internal/checkpoint/checkpoint.go
internal/checkpoint/checkpoint_test.go
internal/clock/clock.go
internal/clock/clock_test.go

This adds a new utility module for measuring time by defining checkpoints.
I plan to use this throughout the code for logging and metrics purposes.

feat: New checkpoint module

---

docs/hack/quickstart.md

This PR updates the QuickStart guide to include an alternative method for setting up an Argo CD Agent environment using OCM.
NA
**Checklist**

docs: Update the quickstart guide with a link to OCM-io and Argo CD Agent OCM AddOn integration solution

---

internal/session/session.go
internal/session/session_test.go
principal/apis/eventstream/eventstream.go
principal/auth.go

It provides functions to inspect and manipulate session information in the context.
Fixes #?
**Checklist**

chore: Improve handling of auth data in context

---

hack/dev-env/setup-vcluster-env.sh

This stores the admin password, generated by the scripts, in a secret for later reference.
Fixes #?
**Checklist**

chore(dev-env): Store generated admin password in a secret

---

.github/workflows/ci.yaml

chore(build): Pin microk8s to 1.31 channel

---

hack/dev-env/setup-vcluster-env.sh

Some users might not have a 192.168.56.0/24 network on their box, or might actually use that for different purposes. This PR introduces the `LB_NETWORK` environment variable, which lets users give the /24 network to use for the load balancer on the control plane.
Fixes #?
**Checklist**

chore(dev-env): Allow for none-default load balancer network

---

principal/resourceproxy/resourceproxy.go

Just removes some dead code from the resourceproxy package.
Fixes #?
**Checklist**

chore: Remove dead code

---

internal/version/version.go

This fix allows version information to be set by the linker through linker flags.
Fixes #?
**Checklist**

fix: Allow version information to be set by linker

---

Makefile

Set some version information during build time
Fixes #?
**Checklist**

build: Set version information during build time

---

hack/release.sh

Add a small script that helps with building and publishing release assets.
Fixes #?
**Checklist**

chore: Add release helper script

---

.github/workflows/semantic-pr.yaml

Use an action to make sure PR titles match [Conventional Commits spec](https://www.conventionalcommits.org/en/v1.0.0/)
Fixes #?
The check uses `pull_request_target` as trigger, so changes to the workflow are not reflected in the CI run with the PR. I have validated the check runs correctly by using `pull_request` target temporarily, and it works as expected.
**Checklist**

build(github): Lint PR titles

---

agent/agent.go
agent/agent_test.go
agent/options.go
cmd/agent/main.go
hack/dev-env/start-agent-autonomous.sh
hack/dev-env/start-agent-managed.sh

Include a simple health check server to verify whether the agent is up and running.
Fixes #?
**Checklist**

feat: include a simple health check server for agent

---

cmd/agent/main.go
cmd/principal/main.go

This PR is to modify pprof implementation.

feat: update pprof implementation

---

principal/event.go
principal/event_test.go

The principal should update the app if it already exists while handling a create event. This could result in a race condition leading to occasional e2e test failures. 
Here's a scenario when an e2e test could fail in autonomous mode:
1. The agent sends a `create` event to the principal and waits for an ACK
2. Simultaneously, the agent sends a `specUpdate` event to the principal responding to a `resourceResync` request.
3. The `specUpdate` event replaces the waiting `create` event in the queue since they have the same ID 
4. The principal ignores the create event since the app already exists.
5. Before the agent could send the `specUpdate` event, it could receive an ACK from the agent and remove the `specUpdate` event from the queue. This leads to …

fix: principal should update the app if it already exists in autonmous mode

---

.golangci.yaml
agent/agent.go
agent/inbound.go
cmd/ctl/agent.go
cmd/principal/main.go
internal/manager/application/application.go
internal/manager/appproject/appproject.go
principal/apis/auth/auth.go

Fix all complaints brought up by golangci-lint and remove the temporary staticcheck exclusions.
Fixes #?
**Checklist**

chore(refactor): Fix lint complains and remove exclusions

---

agent/resource.go
agent/resource_test.go
principal/resource.go

This allows fetching the list of available APIs through the resource-proxy.
Fixes #412 
**Checklist**

feat: Allow fetching API groups via resource proxy

---

README.md
docs/configuration/index.md
docs/configuration/principal/index.md

This update makes the top-level README more engaging and brings it up-to-date, too.
Fixes #?
**Checklist**

docs: Make the top-level README more engaging

---

docs/configuration/agent/configuration.md
docs/configuration/principal/configuration.md
mkdocs.yml

docs: Document agent and principal parameters and flags

---

docs/user-guide/live-resources.md

The agents need enhanced Kubernetes RBAC capabilities for most of the live resource proxy functionality to work properly. This documents what needs to be done, and tells the user that by default, the permissions are not enough.
Fixes #?
**Checklist**

docs: Document agent RBAC requirement for resource proxy

---

docs/user-guide/migration.md
mkdocs.yml

This PR introduces an initial version of a guide outlining how to migrate from classical Argo CD multi-cluster setup to an agent based installation.
It's by no means meant to be a complete guide, rather a rough guide outlining the tasks and risks involved in a migration.
Fixes #?
**Checklist**

docs: Migration guide

---

docs/features/index.md
docs/index.md

This PR reworks significant portions of the general overview and features pages in the docs.
Assisted by Cursor.
Fixes #?
**Checklist**

docs: Rework general overview and features pages

---

ROADMAP.md

This updates ROADMAP.md to current realities and plans.
Fixes #?
**Checklist**

docs: Update roadmap document to reflect current state

---

docs/getting-started/kubernetes/index.md

The getting started guide had a discrepancy: The principal was set up to accept mtls authentication, but the agent was configured to use userpass auth. This obviously will not work. This PR changes the getting started guide to configure the agent using mTLS authentication instead.
Fixes #?
**Checklist**

docs: Use mtls instead of userpass in getting started guide

---

docs/concepts/argocd-integration.md

Assisted-by: Cursor
Finalize and update the documentation about Argo CD integration patterns.
Fixes #?
**Checklist**

docs: Finish and update the Argo CD Integration patterns docs

---

docs/getting-started/kubernetes/index.md

docs: fix a few issues with the k8s getting started guide: https://argocd-agent.readthedocs.io/latest/getting-started/kubernetes/
- Add the missing propagate CA step
- Add the missing propagate AppProject step
- Fix the principal app example by populating the destination server with the correct url
- Add another troubleshooting item regarding missing server.secretkey 
- When I get to the verify agent secrets step from the guide, I got
```
$ kubectl get secret argocd-agent-ca -n argocd --context kind-cluster1
Error from server (NotFound): secrets "argocd-agent-ca" not found
```
That's because the guide doesn't have the CA propagation step.
- If I don't propagate (or manually create) the AppProject resource on …

docs: fix a few issues with the k8s getting started guide
