- README.md
Simple fix to the README file where the quickstart guide link is pointing at the wrong path.
> docs: fix quickstart link in readme

- cmd/agent/main.go
- cmd/cmd/log.go
- cmd/principal/main.go
New command line parameter `--log-format` for agent and principal.
For now, accepts one of `text` and `json` arguments to set log format accordingly.
> feat: Support setting log format

- agent/agent.go
- agent/agent_test.go
- agent/connection.go
- agent/inbound_test.go
- cmd/agent/main.go
- internal/auth/userpass/userpass.go
- internal/backend/interface.go
- internal/backend/kubernetes/application/kubernetes.go
- internal/event/event.go
- internal/informer/application/appinformer.go
- internal/informer/application/options.go
- internal/informer/informer.go
- internal/manager/application/application.go
- internal/manager/application/application_test.go
- internal/queue/queue.go
- pkg/client/remote.go
- pkg/client/remote_test.go
- principal/apis/eventstream/eventstream.go
- principal/listen.go
- principal/options.go
- principal/server.go
- test/e2e/e2e_test.go
This PR:
- Adds comments to important structs/fields within the code.
- Comments describe the behaviour as it currently exists, but I'm happy to revert/modify any items that are expected to have a different future behaviour.
- Adds some sanity tests to code to ensure that agent-only code is only run in agent-only context, and vice versa for principal.
- We don't have E2E tests setup for this repo yet (see issue #137), so I manually verified I've not broken anything by  setting up the demo-env and ensuring the basic workflow still works.
> chore: add additional comments to code/structs,  and sanity tests to verify functions are called within the expected context

- Makefile
- agent/inbound_test.go
- internal/informer/application/appinformer.go
- internal/informer/application/appinformer_test.go
- internal/manager/application/application.go
- internal/manager/application/application_test.go
- principal/server.go
- test/e2e/e2e_test.go
This PR:
- Reduces the visibility of fields that are not currently used by other packages
- As always, happy to revert any changes for cases where there are expected uses for these fields, or some grander vision
- In `ApplicationManager`, renamed `application` field -> `applicationBackend`, to clarify it is a backend for storing applications, and not a specific application itself (which was already pretty obvious from the context, but still IMHO worth renaming)
- Add an initial makefile target for running the E2E tests in `test/e2e` folder
> refactor: reduce visibility of appManager/informer fields, rename application field of ApplicationManager

- agent/agent.go
- agent/inbound.go
- internal/backend/interface.go
- internal/backend/kubernetes/application/kubernetes.go
- internal/backend/kubernetes/application/kubernetes_test.go
- internal/backend/mocks/Application.go
- internal/manager/application/application.go
- internal/manager/application/application_test.go
- pkg/client/remote_test.go
- principal/event.go
- principal/server.go
My understanding of the Application backend abstraction is that it is designed to be agnostic to the particular implementation [1]. And on top of that exists the `ApplicationManager`, which is a generic mechanism for interacting with any backend implementation.
At present we only have the Kubernetes backend, and Kubernetes is our primary interface, so naturally some of the implementation details of that backend will leak out. 
This PR seeks to make a fairly minor change to slightly unleak some of those, as a way to pick some low hanging fruit in this area.
[1] But note that agent role code explicitly states that it requires the Kubernetes-based backend.
**This PR:**
- Agent role code changes:
- Remove direct kubernetes API objects (k8s client-go, argo application client-go, app informer …
> refactor: Reduce dependence on client-go API outside of k8s backend

- cmd/principal/main.go
- pkg/client/remote_test.go
- principal/apis/eventstream/eventstream.go
- principal/event_test.go
- principal/listen_test.go
- principal/server.go
- principal/server_test.go
- test/e2e/e2e_test.go
- test/fake/kube/kubernetes.go
This is a small refactor so that the agent and principal both will have access to a generic Kubernetes API client in addition to the versioned Application client.
It is a prerequisite for some changes to come.
> refactor: Provide additional kubernetes client to servers

- internal/informer/application/appinformer.go
- principal/server.go
This PR is to modify log statement printed while starting `Server` and `AppInformer`
- Now logs in `principal` will look something like this
`time="2024-09-20T17:35:59+05:30" level=info msg="Starting argocd-agent (server) v99.9.9-unreleased (allowed_namespaces=[*])" module=server`
`time="2024-09-20T17:35:59+05:30" level=info msg="Starting app informer (namespaces: *)" module=AppInformer`
- And logs in `agent` will look like this
`time="2024-09-20T17:36:12+05:30" level=info msg="Starting argocd-agent (agent) v99.9.9-unreleased (ns=agent-managed, allowed_namespaces=[], mode=managed)" module=Agent`
`time="2024-09-20T17:36:12+05:30" level=info msg="Starting app informer (namespaces: agent-managed)" module=AppInformer`
Fixes: https://github.com/argoproj-labs/argocd-agent/issues/158
> fix: Namespace displayed on startup logs

- hack/demo-env/setup-vcluster-env.sh
On my Mac, the result of `wc -l` is padded on the left with whitespace, causing the `setup-vcluster-env.sh` script to fail. This PR provides a fix for that.
> chore(scripts): Fix setup script

- hack/demo-env/setup-vcluster-env.sh
The test to detect OpenShift in the `setup-vcluster-env.sh` script
```
if kubectl api-resources | grep -q "openshift.io"; then
OPENSHIFT=true
fi
```
is not working.  `grep -q` will return success as soon as it detects the first match. This will close the pipe between the `kubectl` command and the `grep` command. The `kubectl` command will then try to write its next result to the closed pipe, causing it to error out.  Since the script has set `set -o pipefail`, the entire pipeline will then error out, resulting in the `OPENSHIFT` variable not being set.
This PR fixes this by forcing the `kubectl` step to always exit successfully.
> chore(scripts): Fix OpenShift detection in setup-vcluster-env.sh

- cmd/agent/main.go
- cmd/principal/main.go
- go.mod
- go.sum
- pkg/client/remote.go
- principal/listen.go
- principal/options.go
- principal/server.go
- test/e2e/e2e_test.go
- test/proxy/proxy.go
gRPC relies on HTTP/2 for multiplexing requests and is required for bi-directional streaming. However, intermediate infra components (load balancers, proxy, etc.) could be incompatible with HTTP/2 and may downgrade to HTTP/1.1. For these cases, we provide an option to use gRPC over WebSocket for bi-directional streaming that doesn't require HTTP/2. https://github.com/stackrox/go-grpc-http1 handles the translation between gRPC and WebSocket.
* Flags to enable WebSocket
* Update the principal and the agent code to use the go-grpc-http1 client if the flag is enabled
* e2e tests with a HTTP/2 incompatible reverse proxy
> feat: Remove hard requirements for HTTP/2

- principal/callbacks.go
I'm seeing a panic in the principal when an autonomous app is deleted:
```
time="2024-10-03T14:52:26-04:00" level=debug msg="Processing event" client=agent-autonomous event=io.argoproj.argocd-agent.event.delete incoming= mode=autonomous module=QueueProcessor
time="2024-10-03T14:52:27-04:00" level=debug msg="Removed finalizer for app agent-autonomous/guestbook" application=argocd/guestbook component=DeleteOperation resourceVersion=853
time="2024-10-03T14:52:27-04:00" level=info msg="Deleted application agent-autonomous/guestbook" client=agent-autonomous event=io.argoproj.argocd-agent.event.delete incoming=argocd/guestbook mode=autonomous module=QueueProcessor
time="2024-10-03T14:52:27-04:00" level=warning msg="Could not remove finalizer" application_name=guestbook component=EventCallback …
```
> fix: fix panic in principal on autonomous app deletion

- Dockerfile.agent
- Dockerfile.principal
- Makefile
Small fix to Dockerfiles to avoid getting a warning when running `make image-...`
```                                                                                                                                                                                                                                          
1 warning found (use docker --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
```
Adjust the default image repo from a personal repo to the default deployment repo.
> fix: casing for Dockerfiles and default make image repo url

- docs/hack/quickstart.md
Documentation fixes to [quickstart](https://github.com/argoproj-labs/argocd-agent/blob/main/docs/hack/quickstart.md).
1) After the step `kubectl apply -n argocd -k install/kubernetes/principal`, the principal agent pod is not coming up with the error:
```
MountVolume.SetUp failed for volume "userpass-passwd" : secret "argocd-agent-principal-userpass" not found
```
Added a documentation step to create the `argocd-agent-principal-userpass` secret.
Addressed similar issue with the missing agent secret.
2) Adjusted the network connection requirement to match the repo README: https://github.com/argoproj-labs/argocd-agent?tab=readme-ov-file#status-and-current-limitations 
3) Fixed the agent manifest deploy path.
> docs: quickstart guide - manual secret creations, network connection requirement, and agent apply path

- Dockerfile.agent
I am trying to start the agent but the agent pod is failing with the error
```
Error: container has runAsNonRoot and image will run as root (pod: "argocd-agent-agent-74b8b74b5b-9vlbj_argocd(b547aa02-a3ca-4b8c-b26b-fe1aa1aaeb4c)", container: argocd-agent-agent)
```
This fix is to make sure the image is building with a non-root user. I copied the user ID from the principal Dockerfile.
> fix: agent pod is not starting because the image is running as root

- cmd/principal/main.go
- internal/informer/appproject/projectinformer.go
The principal agent pod kept crashlooping with the error:
```
[FATAL]: Could not parse auto namespace labels: invalid label '': has no value
```
I am using the default values so the auto namespace labels is an empty string.
This fix is to ensure that the principal can properly start with the default case.
Also contains a minor logging fix to address the following:
```
level=info msg="Listing AppProjects &{0xc0002579a0 }" module=AppProjectInformer
```
> fix: principal agent not starting up with the default autoNamespaceLabels config

- hack/demo-env/README.md
- hack/demo-env/setup-vcluster-env.sh
- hack/demo-env/start-agent-autonomous.sh
- hack/demo-env/start-agent-managed.sh
- hack/demo-env/start-principal.sh
I've tried to setup the demo/dev env and encountered a few issues. This PR is to address those issues:
1) When I ran the `setup-vcluster-env.sh` script, got the following error:
```
--> Creating vcluster control-plane
18:40:36 fatal unknown flag: --switch-context
ERROR: Error occurred, terminating.
```
`switch-context` is no longer a valid flag for `vcluster create` in vcluster version 0.20.1 stable and there are no similar replacement flags. After I removed the flag, the script ran fine and ultimately the demo/dev env setup was successful so for now I think it's safe to remove this flag.
2) When I ran the `start-*` scripts, I got the following error:
```
set: Illegal option -o pipefail
```
The pipefail option seems to be a [bash specific …
> fix-demo: misc demo related fixes

- hack/demo-env/gen-creds.sh
The gen-creds.sh script sets up an environment variable alias for pwmake in case the system has pwgen instead, but then doesn't use it.
> fix: fix gen-creds.sh

- hack/demo-env/README.md
- hack/demo-env/apps/autonomous-guestbook.yaml
- hack/demo-env/apps/managed-guestbook.yaml
- hack/demo-env/ocm/README.md
- hack/demo-env/ocm/agent-autonomous/kustomization.yaml
- hack/demo-env/ocm/agent-autonomous/ocm-agent-auto-addontemplate.yaml
- hack/demo-env/ocm/agent-autonomous/ocm-agent-auto-cmaddon.yaml
- hack/demo-env/ocm/agent-autonomous/ocm-agent-auto-maddon.yaml
- hack/demo-env/ocm/agent-managed/kustomization.yaml
- hack/demo-env/ocm/agent-managed/ocm-agent-managed-addontemplate.yaml
- hack/demo-env/ocm/agent-managed/ocm-agent-managed-cmaddon.yaml
- hack/demo-env/ocm/agent-managed/ocm-agent-managed-maddon.yaml
- hack/demo-env/ocm/principal/kustomization.yaml
- hack/demo-env/ocm/principal/principal-clusterrole.yaml
- hack/demo-env/ocm/principal/principal-clusterrolebinding.yaml
- hack/demo-env/ocm/principal/principal-deployment.yaml
- hack/demo-env/ocm/principal/principal-params-cm.yaml
- hack/demo-env/ocm/principal/principal-role.yaml
- hack/demo-env/ocm/principal/principal-rolebinding.yaml
- hack/demo-env/ocm/principal/principal-sa.yaml
- hack/demo-env/ocm/principal/principal-service.yaml
Enhance the demo/dev guide docs with steps to run the agent components using [Open Cluster Management](https://open-cluster-management.io/) and it's [addon framework](https://open-cluster-management.io/docs/concepts/addon/).
> docs: demo/dev guide - add running argocd agent components in clusters using open cluster management

- .github/workflows/ci.yaml
- internal/informer/appproject/projectinformer.go
- internal/informer/informer.go
- internal/informer/informer_test.go
- internal/manager/application/application.go
- internal/manager/appproject/appproject.go
- internal/metrics/metrics.go
- internal/metrics/server.go
- principal/server.go
This PR adds metrics to the generic informer, conveniently handled within the callbacks.
Additionally, it adds some unit tests for the informer package.
The next step will move the existing application informer to use the generic informer, too.
> feat: Add informer metrics

- hack/demo-env/agent-autonomous/kustomization.yaml
- hack/demo-env/agent-managed/kustomization.yaml
- hack/demo-env/control-plane/kustomization.yaml
- hack/demo-env/setup-vcluster-env.sh
For the demo/dev env script, the ArgoCD deployments installed on the hub and spoke are using the `latest` tag instead of the release tag. This is due to the kustomization yamls are all using `?ref=stable` but the argocd github repo still references latest (bug with argocd repo?). For example, https://github.com/argoproj/argo-cd/blob/stable/manifests/base/server/argocd-server-deployment.yaml#L21
This fix is to replace the latest tag with the latest stable release tag.
> chore(scripts): fix argocd deploy release version

- internal/informer/appproject/projectinformer.go
- internal/informer/appproject/projectinformer_test.go
The AppProject informer should not be cluster-scoped and instead operate in a single namespace.
Fixes #213
> fix: AppProject informer should be single namespace

- cmd/cmd/log.go
This PR fixes log output when the log level is trace. Prior to this fix, trace messages would disappear in the nirvana.
> fix: Fix trace log level output

- docs/hack/quickstart.md
- hack/demo-env/ocm/README.md
When installing on an OpenShift clusters, it would be easy if customers can directly install the `argocd-agent` components directly from github without cloning.
> Minor fixes for documentation to install principal/agent

- hack/demo-env/Makefile
- hack/demo-env/Procfile
This PR is to make use of `goreman` to run principal and agent in same console, this would make debugging easy as logs of both components would be printed in same console, also it would help to understand the order of execution of agent and principal code blocks.
> chore: use goreman to start principal and agent

- agent/agent.go
- agent/connection.go
- agent/inbound.go
- internal/event/event.go
- internal/event/event_test.go
- principal/apis/eventstream/eventstream.go
- principal/event.go
- principal/event_test.go
* Added a new event type `ACK` that is sent by the principal/agent when an event is processed successfully.
* `EventWriter` keeps track of the latest events and sends them on the gRPC stream. Both the agent and the principal will add events to the `EventWriter` instead of directly sending them to the gRPC stream. The `EventWriter` will send the events with exponential backoff until we receive an ACK from the other side. It continuously loops over the waiting events and sends them to the other side with minimal delay. The goal was to propagate the events as soon as possible with minimal delay and without blocking the other events.
* Added `UID` (resourceID) and `resourceVersion` (eventID) to the cloudevent as extensions. We do this to map an event to a particular state of a resource. For …
> feat: resend events with exponential backoff and wait for ACK

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/task.md
- .github/PULL_REQUEST_TEMPLATE.md
Add initial, basic issue/pull request template. Template contents are based on sibling project 'argocd-operator' in the argoproj-labs org, with some customization.
> chore(github): Add initial issue/pull request template

- README.md
- docs/CONTRIBUTING.md
As requested as part of 'argocd-agent' project planning, I had added some initial code contribution guidelines. These are a mix of best practices from other  projects, and our current practices within the codebase.
These are meant to supplement the project contribution guidelines described within `README.md` at the root of the repository.
If reviewers have suggestions for changes to proposed guidelines, or new suggestions for guidelines, then feedback is  welcome!
> docs: Initial code contribution guidelines documentation

- hack/demo-env/agent-autonomous/kustomization.yaml
- hack/demo-env/agent-managed/kustomization.yaml
- hack/demo-env/control-plane/kustomization.yaml
- hack/demo-env/setup-vcluster-env.sh
This change shallow clones the Argo CD repository to a temp path and points the kustomize bases to use those, instead of always pulling from github.com.
> chore(demo-env): Use local argo-cd manifests for speeding up kustomize

- agent/inbound.go
- agent/inbound_test.go
- internal/manager/application/application.go
- internal/manager/application/application_test.go
- internal/manager/appproject/appproject.go
- internal/manager/appproject/appproject_test.go
- internal/manager/manager.go
Currently, we don't handle a case where the incoming app/app project could have a different source UID than the resource on the cluster with the same name and namespace. This indicates that the existing resource in the agent was created from a different resource in principal which no longer exists. We annotate the resources in the agent with the source UID to track their source of truth.
For more details: https://github.com/argoproj-labs/argocd-agent/pull/225#discussion_r1851965152
1. An app is present on both the principal and the agent
2. Principal process stops
3. User deletes the app 
4. Principal starts again and the user creates a new app
5. The agent couldn't differentiate between the new and old apps. …
> feat: handle UID mismatch between incoming and existing resources

- agent/connection.go
- internal/kube/client.go
- principal/event.go
* Check if the error is retryable/transient.
* Don't send an ACK for retryable errors so that the principal can resend events.
Fixes https://github.com/argoproj-labs/argocd-agent/issues/243
**Checklist**
> fix: resend events only for retryable errors

- agent/inbound.go
- agent/inbound_test.go
- internal/manager/application/application.go
- internal/manager/application/application_test.go
- internal/manager/appproject/appproject.go
- internal/manager/appproject/appproject_test.go
When the principal restarts, the informer reconciles the existing resources and they are sent to the agent as `Create` events.  However, the agent may drop these `Create` events if the resource exists. The agent may miss updates by dropping these events. Consider the following scenario:
1. The principal and the agent are in sync
2. Principal process stops
3. The user updates the app
4. The principal restarts and sends the latest resources as `Create` events.
5. The agent will drop the `Create` events since the resource already exists.
6. Now the agent is out of sync with the principal until the next update event.
This PR updates the logic to handle create events. The agent now checks if the resource already exists and updates the resources …
> fix: update the existing resources when the principal restarts

- agent/inbound.go
- agent/inbound_test.go
In https://github.com/argoproj-labs/argocd-agent/pull/266 we update the resource if it already exists while handling create events. However, since the principal will send the latest event for a resource the agent may sometimes receive an update event for a resource that doesn't exist yet. For example:
1. The user creates an app on the control plane and updates it immediately before the create event is sent to the agent. 
2. Sometimes the principal may send the update event since it is the latest one.
3. The agent must create the incoming app since it doesn't exist
Fixes #?
**Checklist**
> fix: create the resource if it doesn't exist while handling update events

- agent/agent.go
- agent/agent_test.go
- agent/connection.go
- agent/outbound.go
- cmd/agent/main.go
- internal/backend/interface.go
- internal/backend/kubernetes/namespace/kubernetes.go
- internal/queue/queue.go
- internal/queue/queue_test.go
- internal/session/session.go
- internal/session/session_test.go
- pkg/types/types.go
- principal/apis/eventstream/eventstream.go
- principal/apis/eventstream/eventstream_test.go
- principal/apis/eventstream/mock/mock.go
- principal/auth.go
- principal/callbacks.go
- principal/server.go
- principal/server_test.go
- test/e2e/e2e_test.go
See https://github.com/argoproj-labs/argocd-agent/pull/225#discussion_r1851955435 for more details.
Currently, the principal removes the queue when the agent disconnects and drops all the incoming events from the informer. When the agent connects back it may miss the updates and be out of sync from the principal.  For example:
1. The principal and the agent are in sync
2. Agent disconnects
3. The user updates the application. But the principal discards them since there is no agent
4. The agent connects back and is now out of sync with the principal.
There are two solutions to this problem:
1. The principal shouldn't remove the queue and reuse it when the agent connects again. The principal will just send the events from the queue when the agent …
> feat: store the informer events even if the agent is not connected

- agent/inbound.go
- agent/inbound_test.go
Use projectManager instead of appManager when handling AppProject events from the informer.
Fixes #?
**Checklist**
> fix: use project manager to process incoming AppProjects

- go.mod
- go.sum
Updates glog, also for dependencies (fixes [CVE-2024-45339](https://github.com/advisories/GHSA-6wxm-mpqj-6jpf))
Fixes #?
**Checklist**
> build(deps): Bump github.com/golang/glog from 1.2.3 to 1.2.4

- .github/workflows/ci.yaml
See https://github.com/actions/cache/discussions/1510
Our builds fail currently because we're using a deprecated version of `actions/cache`
Fixes #?
**Checklist**
> chore(build): Bump actions/cache to v4.2.0 due to deprecation

- principal/resource.go
- principal/resource_test.go
Small fix in the regular expression used by the resource proxy to also allow requests for `/api` and `/apis` without any further qualifications, to get a list of available APIs (i.e. `kubectl api-resources`).
Also adds some unit tests for the regexp itself.
Fixes #?
**Checklist**
> fix: Allow resource proxy to proxy /api and /apis requests

- agent/outbound.go
- agent/outbound_test.go
This PR changes the event emitting behavior for agents slightly. Now, the agent will neither send create nor delete events to the principal when in managed mode, because these events should originate at the principal anyway.
Fixes #?
**Checklist**
> fix: More refined event emitting for the agent

- README.md
In the current dev/demo portion of the [README](https://github.com/argoproj-labs/argocd-agent?tab=readme-ov-file#hacking-testing-demoing), the link to the [some scripts and docs](https://github.com/argoproj-labs/argocd-agent/tree/main/hack/demo-env) is broken.
This is a quick chore fix to update the link to the correct location.
NA chore fix.
**Checklist**
> chore: Fix the README link to dev/demo env

- cmd/agent/main.go
- cmd/principal/main.go
- hack/dev-env/start-agent-autonomous.sh
- hack/dev-env/start-agent-managed.sh
- internal/env/env.go
- internal/env/env_test.go
- pkg/client/remote.go
- principal/listen.go
- principal/options.go
- principal/server.go
This PR is to introduce a configurable periodic ping to keep connection alive between agent and principal using [grpc keepalive feature](https://grpc.io/docs/guides/keepalive/). 
By default it is disabled and to enable it you need to set value of `keep-alive-ping-interval` in startup script or set env variable `KEEP_ALIVE_PING_INTERVAL`  at agent side and at principal side you have to set value of `wait-duration-for-agent-ping` in startup script or set value of env variable `WAIT_DURATION_FOR_AGENT_PING` .
Fixes https://github.com/argoproj-labs/argocd-agent/issues/171
> feat: support periodic ping to principal for keeping connection alive

- hack/dev-env/apps/managed-guestbook.yaml
Currently, the sample app in the dev-env for managed mode is created in the argocd namespace. Whereas, we expect the resource to be created in the agent namespace which is `agent-managed` on the control plane.
Fixes #?
**Checklist**
> fix: change the app namespace to match the agent namespace

- .github/workflows/ci.yaml
- Makefile
The `start-e2e2` target requires goreman to run successfully. This PR installs goreman as a prerequisite for the `start-e2e2` target.
Fixes #?
**Checklist**
> chore(e2e): Install goreman as prerequisite

- Makefile
- agent/agent.go
- agent/connection.go
- agent/connection_test.go
- agent/inbound.go
- agent/inbound_test.go
- agent/outbound.go
- internal/event/event.go
- internal/manager/application/application.go
- internal/manager/appproject/appproject.go
- internal/resources/resources.go
- internal/resources/resources_test.go
- internal/resync/resync.go
- internal/resync/resync_test.go
- pkg/types/types.go
- principal/apis/eventstream/eventstream.go
- principal/callbacks.go
- principal/event.go
- principal/event_test.go
- principal/listen.go
- principal/server.go
- principal/server_test.go
- test/e2e2/resync_test.go
Currently, the agent and the principal might get out of sync when they miss events that occur when they are down. Jonathan proposed an [algorithm](https://docs.google.com/document/d/1NwQaYxmRva8irx_clPTqRu_YQ8MNeFNXSTJoOgv7ZRs/edit?tab=t.0#heading=h.u46lpf9a77zp) with message types that would handle these scenarios. This PR implements the proposed logic to resync the agent/principal when they restart.
Changes introduced:
- New event types that are exchanged when the agent/principal restarts. These events are exchanged only ONCE when the process restarts
- Use checksums to avoid redundant events. If the checksums match, we can assume that the components are in sync
- Support for both managed and autonomous mode
- Unit tests
Simple sequence diagram …
> feat: agent and principal should resync on start up

- Makefile
- cmd/principal/main.go
- go.mod
- hack/dev-env/Procfile.e2e
- hack/dev-env/start-agent-managed.sh
- hack/dev-env/start-principal.sh
- internal/argocd/cluster/cluster.go
- internal/argocd/cluster/cluster_test.go
- internal/argocd/cluster/informer_test.go
- internal/argocd/cluster/manager.go
- internal/argocd/cluster/manager_test.go
- principal/apis/eventstream/eventstream.go
- principal/apis/eventstream/eventstream_test.go
- principal/listen.go
- principal/options.go
- principal/server.go
- test/e2e2/clusterinfo_test.go
- test/e2e2/fixture/cluster.go
- test/run-e2e.sh
This PR is to expose agent's connection status and other details via Cluster resource.
Fixes https://github.com/argoproj-labs/argocd-agent/issues/130
To update cluster info Principal needs to connect with Redis. For this I a using LoadBalancer hostname, (which could be changed to internal address when we run within container) ss of now for development in local we are using LoadBalancer.
> feat: Agent's connection info should be exposed in cluster resource

- cmd/agent/main.go
- hack/dev-env/start-agent-autonomous.sh
- hack/dev-env/start-agent-managed.sh
- pkg/client/remote.go
- principal/listen.go
This PR enables users to send/receive compressed data stream between Principal and Agent. User can enable/disable compression by setting `enable-compression` flag to `True` or setting `ARGOCD_AGENT_ENABLE_COMPRESSION` env variable at agent side. There is no action needed at Principal because at server side registered compressors will be used automatically. As of now `gzip` compression is used.
Fixes https://github.com/argoproj-labs/argocd-agent/issues/113
> feat: enable compression for communication over gRPC

- internal/argocd/cluster/cluster_test.go
This PR is to fix a flaky unit test, where `Test_UpdateClusterInfo` test fails sometimes because getClusterInfo() takes more than 1 second to fetch data from Redis cache. It is fixed by increasing time range. It can be tested by running below command to confirm.
`go test -run Test_UpdateClusterInfo -count 100 -failfast`
> chore: fix flaky unit test

- cmd/principal/main.go
Introduce a `--version` flag to the principal command, allowing users to display version information for the argocd-agent. An optional `--version-format` flag specifies the output format (text, json, or json-indent).
Fixed #354
i implemented the `--version` flag in the same way as it is currently implemented in the agent. is there a reason this is not a separate sub command in both cases? i can make that change as well, if it is preferred.
**Checklist**
* [] Documentation update is required by this PR (and has been updated) OR no documentation update is required.
> feat: Add version flag to principal command

- Makefile
Agent configuration is created in the `start-e2e` target. However, we run the `start-e2e` target in the background, and GH actions will progress quickly to the next step in the workflow.
Sometimes, when the runner is a little slow, the agent configuration does not yet exist when required.
This PR moves the agent configuration creation to `setup-e2e` target.
Fixes #?
**Checklist**
> chore(e2e): Fix race condition for agent configuration

- agent/agent.go
- agent/connection.go
- agent/connection_test.go
- agent/inbound.go
- agent/outbound.go
- agent/outbound_test.go
Since each agent connects to a single principal, the queue name can be a constant. We can keep the queue open even if the agent is disconnected from the principal.
Fixes #?
**Checklist**
> fix: agent should use the default queue name instead of client ID

- internal/event/event.go
- internal/queue/queue.go
- principal/apis/eventstream/eventstream.go
- principal/apis/eventstream/eventstream_test.go
- principal/callbacks.go
- principal/listen.go
- principal/server.go
Currently, we remove the queue/eventwriter in the Subscribe() when an agent disconnects with the principal. We recreate the queue if there are new events from the informer. However, the queue/eventwriter could have some pending events yet to be transmitted. Removing them could lead to losing these pending events. We want the queue to keep the events, even if there is a transient disconnect between the agent and the principal.
1. Don't remove the queue and the eventwriter on disconnect
2. sendFunc() should exit when the client context is cancelled
3. Remove the queue/eventwriter when the namespace is deleted.
Fixes #?
**Checklist**
> fix: don't remove the queue/eventwriter on disconnect

- docs/operations/metrics.md
- docs/operations/profiling.md
- mkdocs.yml
This PR is to add documentation for ArgoCD agent metrics, also there is a minor change for pprof implementation.
> docs: Add docs for metrics and profiling

- cmd/agent/main.go
- cmd/ctl/agent.go
- cmd/ctl/ca.go
- cmd/ctl/main.go
- cmd/principal/main.go
- hack/dev-env/create-agent-config.sh
- hack/dev-env/start-principal.sh
- internal/config/constants.go
- internal/tlsutil/generate.go
- internal/tlsutil/generate_test.go
- pkg/client/remote.go
- principal/options.go
Consolidates and simplifies previous `argocd-agentctl ca` command into `argocd-agentctl pki`, including the ability to issue client certificates for the agents.
Fixes #?
* Functionality is mostly tested by setting up the end-to-end tests. The scripts make use of the pki command.
* Output of the pki command is intended for test/dev purposes only. It's not considered production grade PKI.
**Checklist**
> feat: PKI manipulation using CLI

- agent/agent.go
- cmd/principal/main.go
- hack/dev-env/start-agent-autonomous.sh
- hack/dev-env/start-agent-managed.sh
- hack/dev-env/start-principal.sh
- pkg/client/remote.go
- principal/options.go
This fix enables the principal to load the CA certificate from a secret, like the agent does.
Also, it enables mTLS authentication in the dev env, replacing the deprecated userpass authentication.
Fixes #?
**Checklist**
> fix: Load CA certificate from a secret

- .github/workflows/ci.yaml
- .golangci.yaml
- Makefile
This updates the version of golangci-lint to 2.1.6 and the corresponding action to 8.0.0.
Fixes #?
There are a few exclusion I had to add to the configuration, which are mainly style related. We will fix them one after the other in subsequent PRs.
**Checklist**
> chore(build): Upgrade golangci-lint to v2.1.6

- install/kubernetes/agent/agent-metrics-service.yaml
- install/kubernetes/agent/kustomization.yaml
- install/kubernetes/principal/kustomization.yaml
- install/kubernetes/principal/principal-metrics-service.yaml
This PR is to add kube manifests to expose metrics servers running on principal and agent via a Service.
> build: Add service manifest to expose metrics server

- hack/dev-env/start-agent-autonomous.sh
- hack/dev-env/start-agent-managed.sh
- hack/dev-env/start-principal.sh
Sometimes, the default trace level used in the dev-env can be overwhelming. This allows the log level to be set by using `ARGOCD_AGENT_LOG_LEVEL` environment variable.
Fixes #?
**Checklist**
> chore(dev-env): Allow log level to be set from env

- agent/agent.go
- agent/inbound.go
- agent/outbound.go
- internal/cache/appcache.go
- internal/cache/appcache_test.go
- internal/manager/application/application.go
- internal/manager/application/application_test.go
- test/e2e2/cache_test.go
This PR is to fix a bug when user makes any changes in application on managed-cluster instead of principal, but managed-agent does not revert those changes. As principal is source of truth in managed mode changes in managed cluster should not be allowed.
Fixes https://github.com/argoproj-labs/argocd-agent/issues/238
> fix: Direct changes in app on managed-cluster are not reverted by agent

- .gitignore
- hack/secret-to-kubeconf/README.md
- hack/secret-to-kubeconf/clustersecret-to-kubeconf.py
- hack/secret-to-kubeconf/requirements.txt
- hack/secret-to-kubeconf/test_cluster_secret.py
This script allows you to create a kubeconfig file from Argo CD's cluster secrets. It's intended for development purposes, e.g. to debug the resource proxy.
It's been vibe coded using Cursor.
Fixes #?
**Checklist**
> chore: Add script to convert Argo CD cluster secrets to kubeconf

- install/kubernetes/agent/agent-deployment.yaml
- install/kubernetes/agent/agent-params-cm.yaml
- install/kubernetes/principal/principal-deployment.yaml
- install/kubernetes/principal/principal-params-cm.yaml
Remove hardcoded TLS certificate paths in agent and principal
ConfigMaps to enhance security and avoid potential misconfigurations.
Set default values to empty strings for TLS-related fields.
Fixes #431
a clean installation of either the principal or an agent should only require `argocd-agent-principal-tls` or `argocd-agent-client-tls` with crt/key fields, and `argocd-agent-ca` with crt field.
**Checklist**
> chore: Remove-mounted-tls-secrets

- cmd/agent/main.go
- cmd/principal/main.go
- install/kubernetes/agent/agent-deployment.yaml
- install/kubernetes/agent/agent-params-cm.yaml
- install/kubernetes/principal/principal-deployment.yaml
- install/kubernetes/principal/principal-params-cm.yaml
- pkg/client/remote.go
- principal/options.go
- Introduce flags for specifying TLS secret names in agent and principal commands.
- Update deployment and config maps to reference new TLS secret names.
- Modify functions to accept parameters in a consistent order for better readability (namespace before name)
- Enhance logging for TLS certificate loading from secrets.
This change allows users to configure TLS certificates more flexibly,
improving security and usability in Kubernetes deployments.
Fixes #?
**Checklist**
* [] Documentation update is required by this PR (and has been updated) OR no documentation update is required.
> feat: Add TLS secret name configuration for agent and principal

- cmd/ctl/ca.go
- internal/config/constants.go
Adds a new CLI command `pki propagate` that propagates the principal's PKI CA certificate to the specified agent.
This will ease setup for people testing out the agent.
Fixes #?
1. Initialize a new PKI for the principal: `argocd-agentctl pki init --principal-context vcluster-control-plane`
2. Propagate CA certificate to agent: `argocd-agentctl pki propagate --principal-context vcluster-control-plane --agent-context vcluster-agent-managed`
3. Check that secret `argocd-agent-ca` has been created in `vcluster-agent-managed` context's namespace `argocd` (by default) and that the field `ca.crt` holds the principal's PKI CA certificate.
**Checklist**
> feat: CLI command to propagate CA cert to agents

- cmd/ctl/agent.go
- cmd/ctl/agent_test.go
The `agent create` command of the `argocd-agentctl` CLI takes a `--resource-proxy-server` parameter to specify the location of the resource server. The value given is validated, and needed to be a valid IP address and port combination. However, in the cluster, the hostname is most likely to be specified as DNS name, i.e. the name of the service of the resource proxy's endpoint.
Fixes #?
Create an agent configuration that points the RP to a DNS name, e.g.
```
argocd-agentctl agent create --resource-proxy-server resource-proxy:9090 agent-test
```
**Checklist**
> fix(cli): Allow DNS names for resource proxy host in agent config

- agent/inbound.go
- agent/inbound_test.go
- test/e2e2/sync_test.go
We don't add source UID annotations for resources on autonomous agents since it is the source of truth. However, when the control plane sends update events due to sync/refresh, the agent used to look for this annotation and discard the event. This PR fixes this issue by only comparing the source UID for managed agents.
Fixes #446 
**Checklist**
> fix: don't compare source UID for apps on autonomous agents

- cmd/argocd-agent/principal.go
- install/kubernetes/agent/agent-deployment.yaml
- install/kubernetes/agent/agent-healthz-service.yaml
- install/kubernetes/agent/agent-params-cm.yaml
- install/kubernetes/agent/kustomization.yaml
- install/kubernetes/principal/kustomization.yaml
- install/kubernetes/principal/principal-deployment.yaml
- install/kubernetes/principal/principal-healthz-service.yaml
- install/kubernetes/principal/principal-params-cm.yaml
- principal/options.go
- principal/server.go
- test/e2e2/cache_test.go
- test/e2e2/fixture/toxyproxy.go
- test/e2e2/resync_test.go
This PR is to add health check endpoint to principal, which can be used to verify server readiness. This would fix the issue https://github.com/argoproj-labs/argocd-agent/issues/422, where principal is not fully started but tests still executed which causes test failure.
This PR also exposes health check via a service for both Principal and Agent.
> feat: add health check endpoint for principal

- agent/outbound.go
- agent/outbound_test.go
- go.mod
- internal/manager/application/application.go
- internal/manager/application/application_test.go
- principal/callbacks.go
- principal/event.go
- principal/event_test.go
- test/e2e2/delete_test.go
- test/e2e2/fixture/fixture.go
- At present, if you perform a cascade delete on an Argo CD Application from principal, the child resources of that Application will not be deleted on managed-agent.
- This is due to the following, which have been rectified: 
- The Argo CD Application deletion `.metadata.finalizer` was being removed by principal
- Deletion events for managed-agent were not being sent by agent
- Deletion events for managed-agent were not being processed by principal
- Plus updated unit/E2E tests
Fixes #443
> fix: cascaded delete on Application should clean up all managed-agent app resources

- hack/dev-env/apps/autonomous-guestbook.yaml
- hack/dev-env/apps/managed-guestbook.yaml
This PR modifies the example apps to a) use resource proxy as destination in case of the managed agent app, and b) both Applications to use names instead of URLs.
Fixes #?
**Checklist**
> chore(dev-env): Tweak example/test apps to use resource proxy as destination

- mkdocs.yml
Enables the mermaid plugin for mkdocs-material to support rendering of [diagrams](https://squidfunk.github.io/mkdocs-material/reference/diagrams/) in the documentation.
Fixes #?
**Checklist**
> docs: Enable mermaid plugin for mkdocs

- cmd/ctl/ca.go
- cmd/ctl/ca_test.go
The `pki inspect` command now prints information about principal's and resource proxy's certificate along with the CA certificate. This eases troubleshooting and information gathering for admins.
Fixes #?
**Checklist**
> feat(cli): Print more information in `pki inspect` command

- docs/user-guide/appprojects.md
- hack/dev-env/apps/autonomous-guestbook.yaml
- hack/dev-env/apps/autonomous-project.yaml
- principal/event.go
- principal/event_test.go
- test/e2e2/basic_test.go
- test/e2e2/fixture/fixture.go
- test/e2e2/resync_test.go
- test/e2e2/sync_test.go
This PR correctly applies transformations to `.spec.sourceNamespaces` and `.spec.destinations` when an AppProject is synced from an autonomous agent to the principal.
Also, it will not treat the `default` AppProject synced from an autonomous agent in a special way anymore.
Fixes #496
Fixes #497
**Checklist**
> fix: Better transformation of AppProjects from autonomous agents

- test/e2e/fixture/argoclient.go
- test/e2e/rp_test.go
- test/run-e2e.sh
* The e2e test should wait for the resource action to be available. This could prevent a race condition where the test executes the resource action before Argo CD discovers the action.
* Switch to resource action API version V2
Fixes #?
**Checklist**
> test: wait for resource action to be available

- principal/event.go
- principal/redisproxy/redisproxy.go
As originally reported on internal Slack back in July (pre-redis-proxy-PR merge), @jannfis  reported the following redis-proxy-related error message while interacting with Argo CD UI:
`
14:07:00        principal | time="2025-07-08T14:07:00Z" level=error msg="unable to process redis event response" error="error waiting for response to be read: context deadline exceeded" # (...)
`
It was investigated at the time and determined to only be a logging/lack-of-cleanup issue. That is still correct. 
Here is what I wrote at the time:
> * Re: *'error waiting for response to be read: context deadline exceeded'*:
> * This functionally here is correct, but logging can be improved.
> * This error is printed when an event is sent from agent back to principal, …
> fix: close redis proxy connection ID tracker on goroutine end

- install/kubernetes/argo-cd/principal/kustomization.yaml
Removes delete patch commands for repo-server resources.
We'll need repo-server for argocd UI/CLI commands to work. For example : Sync
> fix: Remove delete patch for repo server

- test/e2e/appcache_test.go
- test/e2e/clusterinfo_test.go
- test/e2e/fixture/cluster.go
- test/e2e/fixture/fixture.go
- test/e2e/fixture/toxyproxy.go
This PR is to modify the validation of ClusterCacheInfo.
The test fails sometimes because of delay in ClusterCacheInfo update by Argo CD. 
Here is the scenario when test fails:
1) At 1st second `ClusterCacheInfo` is refreshed by Argo CD periodic update (every 10 seconds).
2) 5th second, app is created by a test, but cache is yet to be refreshed in next iteration.
3) 10th second, cache is refreshed and now it has app count 1.
4) 15th second, last test completed and app is deleted, but again cache is yet to be refreshed on 20 second.
5) 18th second, `Test_ClusterCacheInfo` started and it fetched current number of apps from agent cache (appCountBefore) which is still set to 1 from last iteration (on 10th second).
6) 20th second, cache refreshed and application count is now set to 0 (based on …
> test(e2e): Fix flaky test for ClusterCacheInfo validation

- hack/dev-env/start-agent-managed.sh
- hack/dev-env/start-principal.sh
- test/e2e/fixture/toxyproxy.go
- test/e2e/websocket_test.go
- test/proxy/proxy.go
Port an old e2e test to our current e2e test framework. The test verifies that the agent can connect to the principal via gRPC over websocket when the intermediate proxy downgrades the HTTP/2 request to HTTP/1.1. 
Fixes #?
**Checklist**
> chore: port HTTP/2 downgrade test to current e2e test framework

- Makefile
This adds a new target `cli-all` to the Makefile, which lets users cross-platform build `argocd-agentctl` CLIs for all combinations of supported OS and CPU architectures.
Fixes #?
* Run `make cli-all`
* You should have an `argocd-agentctl_${OS}-${ARCH}` binary for each OS/Arch combination in `dist/`
**Checklist**
> build: Add Makefile target for building all release CLIs

- cmd/ctl/agent.go
- docs/user-guide/adding-agents.md
- go.mod
- hack/dev-env/create-agent-config.sh
The `argocd-agentctl agent create` command asks for a username and password. However, these are NOPs, as neither is used anywhere for authentication or other purposes. It's best to remove them, to prevent confusion.
Fixes #?
**Checklist**
> fix: Remove username/password from CLI's create agent function

- install/kubernetes/agent/agent-clusterrolebinding.yaml
- install/kubernetes/agent/agent-rolebinding.yaml
- install/kubernetes/principal/principal-clusterrolebinding.yaml
- install/kubernetes/principal/principal-rolebinding.yaml
Follow what Argo CD does and set the rolebinding namespace to argocd for both principal and agent
See https://github.com/argoproj-labs/argocd-agent/pull/542#issuecomment-3253788558 for more details.
This default ns has been pretty annoying when setting up the argocd-agent env for some time now. Following the setup/installation steps is arguably the hardest part of this project, so we should make it as simple as possible for beginners.
Fixes https://github.com/argoproj-labs/argocd-agent/issues/403
**Checklist**
> fix: follow what Argo CD does and set the rolebinding namespace to argocd

- docs/getting-started/kubernetes/index.md
Update Getting Started Guide to update principal configuration, we need to add the agent namespace in the `principal.allowed-namespaces` parameter.
> docs: fix principal namespaces config in getting started guide

- principal/auth.go
- principal/auth_test.go
Rejects agents hat use same name as ArgoCD installation namespace
Fixes #510 
JIRA - https://issues.redhat.com/browse/GITOPS-7692
> feat: reject agents that use same name as ArgoCD namespace

- cmd/ctl/main.go
Running `source <(argocd agentctl completion bash)` errors out. This PR fixes the issue.
Fixes #583
> fix: Setting Use for shell completion

- test/e2e/repository_test.go
- test/e2e/resync_test.go
1. Wait for the agent/principal to be ready after the restart
2. Add extra print statements to debug failures
Tested it locally with repetitions and the tests didn't fail. This should hopefully resolve the intermittent failing e2e tests.
Fixes #?
**Checklist**
> fix(e2e): wait for components to be ready after restart
